# Generated by Django 4.1.5 on 2023-01-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackerapi', '0009_remove_habit_id_alter_habit_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='habit',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
